# frozen_string_literal: true

CoreFile = File

module Hosts
  module File # rubocop:disable Style/Documentation
    def parse_file(file)
      entries = []
      CoreFile.foreach(file) do |line|
        next if line.match(/^\s*$/) || line.start_with?(/\s*#/)

        (address, hostname, aliases) = line.split(nil, 3)
        aliases = aliases.empty? || aliases.start_with?('#') ? [] : aliases.split
        index = aliases.index do |entry|
          entry.start_with?('#')
        end
        aliases = aliases.take(index) if index

        entries << [address, hostname, aliases]
      end
      entries
    end

    def write_file(file, body)
      legend = "# hosts(5) file generated by hostsctl(1)\n\n"

      content = "#{legend}#{body}\n"

      CoreFile.write(file, content)
    end
  end
end
